# Generated by Django 4.0.4 on 2022-06-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0002_coursename_type_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursename',
            name='QorDelay',
            field=models.TextField(max_length=4000),
        ),
    ]
