# Generated by Django 4.0.4 on 2022-06-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0003_alter_coursename_qordelay'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_STR', models.CharField(max_length=50)),
            ],
        ),
    ]
