# Generated by Django 4.0.4 on 2022-06-02 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0005_sp_g_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursename',
            name='type_STR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webfront.typestr'),
        ),
        migrations.AlterField(
            model_name='coursetable',
            name='StudProgram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webfront.sp'),
        ),
    ]
