# Generated by Django 4.0.4 on 2022-06-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0006_alter_coursename_type_str_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetable',
            name='CourseFolder',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
