# Generated by Django 4.0.4 on 2022-06-02 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0008_llog_statusflag_alter_llog_coursename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llog',
            name='CourseName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webfront.coursetable'),
        ),
    ]
