# Generated by Django 4.0.4 on 2022-06-19 08:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0010_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='TEMPTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameProcess', models.CharField(max_length=100)),
                ('IDBot', models.CharField(max_length=100)),
                ('IDChat', models.CharField(max_length=100)),
                ('CourseFolder', models.CharField(max_length=100)),
            ],
        ),
    ]
